version: 0.2
phases:
  build:
    commands:
      - branch=`echo $CODEBUILD_INITIATOR | awk -F'-' '{ print $NF }'`  
      - npm ci -automatic
      - cd env/ && bash ./env.sh && cd ..
      - cp env/env-config.js public/
      - npm run build
      - cd build
      - aws s3 sync . s3://apbs-web/$branch/
      - aws cloudfront create-invalidation --distribution-id $CFID --paths '/*'
artifacts:
  files:
    - '**/*'
