version: 0.2
phases:
  build:
    commands:
      - npm ci -automatic
      - cd env/ && bash ./env.sh && cd ..
      - cp env/env-config.js public/
      - npm run build
      - cd build
      - aws s3 sync . s3://apbs-web/test/
artifacts:
  files:
    - '**/*'
